"""Worker variants. All share the humanoid_worker_v1 skeleton and animation library."""

from core.definitions import AnimationLibraryDefinition, MannequinDefinition
from core.definitions import WorkerDefinition as W

ASSETS = [
    W(id="chr_worker_miner_01", seed=1001, budget="worker", smoke=True, role="miner", body_type="standard",
      presentation="masculine", skin_tone="skin_3", hair_style="short", hair_color="hair_brown", beard="full",
      outfit="work_shirt", outfit_colors={"shirt": "shirt_red", "pants": "denim_blue"}, sleeves="rolled",
      helmet="hardhat_lamp", helmet_color="industrial_yellow", gloves="work", equipment=("tool_belt",),
      tool="tool_pickaxe_01", description="Miner with lamp helmet, pickaxe and tool belt"),
    W(id="chr_worker_miner_02", seed=1002, budget="worker", role="miner", body_type="slim",
      presentation="feminine", skin_tone="skin_5", hair_style="ponytail", hair_color="hair_black", beard="none",
      outfit="hivis_vest", outfit_colors={"vest": "hivis_orange", "shirt": "shirt_gray"}, sleeves="long",
      helmet="hardhat_lamp", helmet_color="safety_orange", gloves="work", tool="tool_jackhammer_01",
      description="Drill miner with jackhammer"),
    W(id="chr_worker_engineer_01", seed=1003, budget="worker", role="engineer", body_type="heavy",
      presentation="masculine", skin_tone="skin_1", hair_style="side_part", hair_color="hair_blonde",
      beard="mustache", glasses=True, outfit="hivis_vest", outfit_colors={"shirt": "shirt_blue", "pants": "khaki"},
      helmet="hardhat", helmet_color="white_paint", gloves="none", tool="tool_wrench_01",
      off_hand_tool="tool_toolbox_01", description="Engineer with tool kit and wrench"),
    W(id="chr_worker_engineer_02", seed=1004, budget="worker", role="engineer", body_type="standard",
      presentation="feminine", skin_tone="skin_2", hair_style="bun", hair_color="hair_auburn", beard="none",
      outfit="hivis_vest", outfit_colors={"shirt": "white_shirt", "pants": "denim_dark", "vest": "hivis_yellow"},
      helmet="hardhat", helmet_color="white_paint", gloves="none", tool="tool_tablet_01",
      description="Engineer with tablet"),
    W(id="chr_worker_operator_01", seed=1005, budget="worker", role="operator", body_type="stocky",
      presentation="masculine", skin_tone="skin_6", hair_style="buzz", hair_color="hair_black", beard="goatee",
      outfit="hivis_jacket", outfit_colors={"jacket": "hivis_orange", "pants": "denim_dark"},
      helmet="hardhat", helmet_color="industrial_yellow", ear_protection=True, gloves="work",
      off_hand_tool="tool_remote_control_01", description="Machine operator with remote control and ear defenders"),
    W(id="chr_worker_operator_02", seed=1006, budget="worker", role="operator", body_type="standard",
      presentation="feminine", skin_tone="skin_4", hair_style="short", hair_color="hair_brown", beard="none",
      outfit="hivis_jacket", outfit_colors={"jacket": "hivis_yellow", "pants": "work_brown"},
      helmet="hardhat", helmet_color="machine_blue", ear_protection=True, gloves="work",
      off_hand_tool="tool_radio_01", description="Operator with radio"),
    W(id="chr_worker_hauler_01", seed=1007, budget="worker", role="hauler", body_type="heavy",
      presentation="masculine", skin_tone="skin_4", hair_style="curly", hair_color="hair_black", beard="stubble",
      outfit="work_shirt", outfit_colors={"shirt": "shirt_gray", "pants": "work_brown"}, sleeves="short",
      helmet="beanie", helmet_color="beanie_red", gloves="work", equipment=("backpack",),
      description="Hauler with frame backpack"),
    W(id="chr_worker_hauler_02", seed=1008, budget="worker", role="hauler", body_type="stocky",
      presentation="feminine", skin_tone="skin_3", hair_style="ponytail", hair_color="hair_red", beard="none",
      outfit="coveralls", outfit_colors={"coveralls": "coverall_navy"}, helmet="cap", helmet_color="shirt_red",
      gloves="work", tool="tool_shovel_01", description="Hauler with shovel"),
    W(id="chr_worker_mechanic_01", seed=1009, budget="worker", role="mechanic", body_type="slim",
      presentation="masculine", skin_tone="skin_2", hair_style="short", hair_color="hair_auburn", beard="stubble",
      outfit="coveralls", outfit_colors={"coveralls": "coverall_orange"}, sleeves="rolled", helmet="cap",
      helmet_color="coverall_navy", gloves="rubber", equipment=("pouch",), tool="tool_wrench_01",
      description="Mechanic in coveralls with wrench"),
    W(id="chr_worker_mechanic_02", seed=1010, budget="worker", role="mechanic", body_type="standard",
      presentation="feminine", skin_tone="skin_6", hair_style="bun", hair_color="hair_black", beard="none",
      outfit="coveralls", outfit_colors={"coveralls": "coverall_navy"}, helmet="none", gloves="rubber",
      glasses=True, tool="tool_hammer_01", description="Mechanic with hammer and safety glasses"),
    W(id="chr_worker_geologist_01", seed=1011, budget="worker", role="geologist", body_type="slim",
      presentation="feminine", skin_tone="skin_1", hair_style="long", hair_color="hair_blonde", beard="none",
      outfit="field_vest", helmet="bush_hat", helmet_color="khaki", gloves="none", equipment=("backpack",),
      tool="tool_rock_hammer_01", off_hand_tool="tool_scanner_01", description="Geologist with rock hammer and scanner"),
    W(id="chr_worker_geologist_02", seed=1012, budget="worker", role="geologist", body_type="standard",
      presentation="masculine", skin_tone="skin_5", hair_style="short", hair_color="hair_gray", beard="full",
      outfit="field_vest", outfit_colors={"shirt": "khaki", "vest": "olive"}, helmet="hardhat",
      helmet_color="machine_green", gloves="none", tool="tool_rock_hammer_01", equipment=("pouch",),
      description="Geologist with survey pouch"),
    W(id="chr_worker_supervisor_01", seed=1013, budget="worker", role="supervisor", body_type="heavy",
      presentation="masculine", skin_tone="skin_2", hair_style="short", hair_color="hair_gray", beard="mustache",
      outfit="supervisor", helmet="hardhat", helmet_color="white_paint", gloves="none", equipment=("radio",),
      off_hand_tool="tool_clipboard_01", description="Supervisor with clipboard and radio"),
    W(id="chr_worker_supervisor_02", seed=1014, budget="worker", role="supervisor", body_type="standard",
      presentation="feminine", skin_tone="skin_5", hair_style="bun", hair_color="hair_brown", beard="none",
      outfit="supervisor", outfit_colors={"shirt": "shirt_blue", "tie": "denim_dark"}, helmet="hardhat",
      helmet_color="white_paint", gloves="none", equipment=("radio",), off_hand_tool="tool_tablet_01",
      description="Supervisor with tablet"),
]
