"""Modular mining worker assembly.

    WorkerDefinition(role="miner", body_type="standard", helmet="hardhat_lamp",
                     tool="tool_pickaxe_01", seed=1001)

Components are generated by reusable modules and combined per variant:
body cage -> garments (outfit) -> gloves/boots -> head -> hair/beard ->
headwear, equipment and tools on standard sockets. Every variant shares the
``humanoid_worker_v1`` skeleton and therefore the whole animation library.

Skinned components are merged into one mesh at export (one draw call);
headwear, back/waist equipment and tools stay separate nodes attached to
socket bones, so the game can swap them without touching the rig.
"""

import math

from mathutils import Matrix, Vector

from rigging import human_rig
from utilities.meshkit import Geo

from . import boots as boots_mod
from . import clothing, equipment, hair, head, headwear
from .body import FOOT_L, FOOT_R, BodyCage
from .clothing import leg_zones
from .skinned import SkinnedGeo

OUTFIT_DEFAULTS = {
    "work_shirt": {"shirt": "shirt_blue", "pants": "denim_blue"},
    "hivis_vest": {"shirt": "shirt_gray", "pants": "work_brown", "vest": "hivis_yellow"},
    "hivis_jacket": {"jacket": "hivis_orange", "pants": "denim_dark"},
    "coveralls": {"coveralls": "coverall_orange"},
    "field_vest": {"shirt": "shirt_green", "pants": "khaki", "vest": "canvas_tan"},
    "supervisor": {"shirt": "white_shirt", "pants": "denim_dark", "tie": "tie_red", "vest": "hivis_yellow"},
}


def _outfit(cage, d, colors):
    o = d.outfit
    c = dict(OUTFIT_DEFAULTS.get(o, {}))
    c.update(colors)
    sl = d.sleeves
    g = []
    if o == "work_shirt":
        g.append(clothing.shirt(cage, c["shirt"], sleeves=sl, tucked=True))
        g.append(clothing.pants(cage, c["pants"], fabric="denim", knee_patch=None))
        g.append(clothing.belt(cage))
    elif o == "hivis_vest":
        g.append(clothing.shirt(cage, c["shirt"], sleeves=sl, tucked=True, pockets=False, buttons=False))
        g.append(clothing.pants(cage, c["pants"], fabric="fabric", knee_patch="fabric:work_brown", cargo=True))
        g.append(clothing.vest(cage, c["vest"], stripes=True))
    elif o == "hivis_jacket":
        jacket = clothing.shirt(cage, c["jacket"], sleeves=sl, tucked=False, loose=0.01, pockets=True, buttons=False,
                                name="jacket")
        _stripes(jacket, cage)
        g.append(jacket)
        g.append(clothing.pants(cage, c["pants"], fabric="denim"))
    elif o == "coveralls":
        g.append(clothing.coveralls(cage, c["coveralls"], sleeves=sl))
    elif o == "field_vest":
        g.append(clothing.shirt(cage, c["shirt"], sleeves=sl, tucked=True, buttons=True, pockets=False))
        g.append(clothing.pants(cage, c["pants"], fabric="fabric", cargo=True))
        g.append(clothing.vest(cage, c["vest"], stripes=False, pockets=4, fabric="fabric"))
        g.append(clothing.belt(cage, "leather:leather_tan"))
    elif o == "supervisor":
        g.append(clothing.shirt(cage, c["shirt"], sleeves=sl, tucked=True, pockets=True, buttons=True))
        g.append(clothing.pants(cage, c["pants"], fabric="fabric"))
        g.append(clothing.tie(cage, c["tie"]))
        g.append(clothing.belt(cage, "leather:leather_black", "steel"))
        if c.get("vest"):
            g.append(clothing.vest(cage, c["vest"], stripes=True, over=0.026))
    else:
        raise ValueError(f"unknown outfit '{o}'")
    return g


def _stripes(gm, cage):
    """Reflective bands on a hi-vis jacket (chest + waist + sleeves)."""
    refl = gm.g.mat("reflective")
    for f in gm.g.bm.faces:
        c = f.calc_center_median()
        if 1.105 <= c.z <= 1.15 or 1.285 <= c.z <= 1.33:
            if abs(c.x) < 0.2:
                f.material_index = refl
        if abs(c.x) > 0.3 and 1.12 <= c.z <= 1.19:
            f.material_index = refl


def _body_remains(cage, hidden, skin_key):
    keep = [f for f in cage.bm.faces if f[cage.fzone] not in hidden]
    sg = SkinnedGeo("body")
    sg.subdivide = 1
    from .skinned import copy_cage_faces
    copy_cage_faces(cage, keep, sg, skin_key)
    return sg if keep else None


def _socket_matrix(bone):
    """World rest matrix of a socket bone composed with the authoring-space
    rotation (item +Z up -> socket Y, item -Y front -> socket Z)."""
    sk = human_rig.skeleton()
    spec = sk.by_name[bone]
    head_v = Vector(spec.head)
    y = (Vector(spec.tail) - head_v).normalized()
    z = Vector(spec.z_axis)
    z = (z - y * z.dot(y)).normalized()
    x = y.cross(z)
    m = Matrix((x, y, z)).transposed().to_4x4()
    m.translation = head_v
    return m @ Matrix.Rotation(math.radians(-90.0), 4, "X")


def _attach_tool(ctx, tool_id, socket, label):
    from registry import tools as tool_registry
    from generators.props import tools as tool_gen
    tdef = tool_registry.by_id(tool_id)
    main = ctx.geo(label, attach=socket)
    detail = ctx.geo(label + "_detail", attach=socket, max_lod=0)
    tool_gen.build_tool(tdef.params["kind"], main, detail)
    m = _socket_matrix(socket)
    for g in (main, detail):
        g.transform_all(m)
        g.props["mm_attach_label"] = label
    return tdef


def build(ctx):
    d = ctx.defn
    cage = BodyCage(d.body_type, d.presentation)
    garments = _outfit(cage, d, d.outfit_colors)
    if d.gloves and d.gloves != "none":
        gcol = {"work": "glove_yellow", "rubber": "glove_gray"}.get(d.gloves, "glove_yellow")
        garments.append(clothing.gloves(cage, gcol, fabric="leather"))
    hidden = set()
    for gm in garments:
        hidden |= gm.hides
    hidden |= leg_zones((6, 7)) | {FOOT_L * 100 + i for i in range(10)} | {FOOT_R * 100 + i for i in range(10)}
    skin = d.skin_tone
    shape = head.HeadShape(d.presentation, ctx.rng.child("head"))
    wears_hat = d.helmet not in (None, "none")
    head_sg, head_det = head.build_head(shape, f"face:{skin}", f"eye:{d.eye_color}", d.hair_color and f"hair:{d.hair_color}",
                                        brows=d.brows, ear_key=f"skin:{skin}")
    if d.glasses:
        gl = Geo("glasses")
        equipment.glasses(gl)
        head_det.append_rigid(gl, "head")
    parts = [head_sg]
    hair_sg = hair.build_hair(shape, d.hair_style, d.hair_color, helmet=wears_hat, rng=ctx.rng.child("hair"))
    if hair_sg:
        parts.append(hair_sg)
    beard_sg = hair.build_beard(shape, d.beard, d.hair_color)
    if beard_sg:
        parts.append(beard_sg)
    details = [(head_det, 99)]
    for gm in garments:
        sg, dets = gm.finish()
        if sg.bm.faces:
            parts.append(sg)
        else:
            sg.bm.free()
        details.extend(dets)
    b_sg, b_hard, b_det = boots_mod.build_boots(leather_key="leather:leather_brown" if d.boots != "rubber" else "rubber")
    parts.append(b_sg)
    details.append((b_hard, 99))
    details.append((b_det, 0))              # laces and pull tab: LOD0-only detail
    body = _body_remains(cage, hidden, f"skin:{skin}")
    if body is not None:
        parts.insert(0, body)
    uv_priority = {"head": 1.8, "gloves": 1.3, "body": 1.3, "hair": 1.1, "beard": 1.1, "boots": 0.8}
    for sg in parts:
        obj = sg.to_object(ctx.lib)
        obj["mm_part"] = sg.name
        obj["mm_uv_scale"] = uv_priority.get(sg.name, 1.0)
        ctx.objects.append(obj)
    for det, max_lod in details:
        if det.bm is None or not det.bm.faces:
            continue
        obj = det.to_object(ctx.lib, subdivide=0)
        obj["mm_part"] = det.name
        obj["mm_max_lod"] = int(max_lod)
        obj["mm_uv_scale"] = 1.6 if det.name == "head_details" else 0.8
        ctx.objects.append(obj)
    # Headwear and equipment on sockets (rigid, swappable nodes).
    headwear.build(d.helmet, d.helmet_color,
                   lambda name, max_lod: _attach_geo(ctx, name, "helmet_attachment", max_lod),
                   ear_protection=d.ear_protection)
    for item in d.equipment:
        if item in equipment.BACK_ITEMS:
            m = _attach_geo(ctx, item, "back_equipment", 99)
            dd = _attach_geo(ctx, item + "_detail", "back_equipment", 0)
            equipment.BACK_ITEMS[item](m, dd)
        elif item in equipment.WAIST_ITEMS:
            m = _attach_geo(ctx, item, "waist_equipment", 99)
            dd = _attach_geo(ctx, item + "_detail", "waist_equipment", 0)
            equipment.WAIST_ITEMS[item](m, dd)
        else:
            raise ValueError(f"unknown equipment '{item}'")
    tools = {}
    if d.tool:
        tools["right"] = _attach_tool(ctx, d.tool, "hand_tool.R", "tool_r").id
    if d.off_hand_tool:
        tools["left"] = _attach_tool(ctx, d.off_hand_tool, "hand_tool.L", "tool_l").id
    ctx.character = {"skeleton": human_rig.NAME, "animate": ctx.param("animate", True)}
    cap = ctx.cfg["collision"]["character_capsule"]
    ctx.col_capsule(cap["radius"], cap["height"])
    ctx.metadata["character"] = {
        "role": d.role, "body_type": d.body_type, "presentation": d.presentation, "skin_tone": d.skin_tone,
        "hair": d.hair_style, "beard": d.beard, "outfit": d.outfit, "helmet": d.helmet, "tools": tools,
        "equipment": list(d.equipment), "skeleton": human_rig.NAME,
    }
    ctx.metadata["capsule"] = cap


def _attach_geo(ctx, name, socket, max_lod):
    g = ctx.geo(name, attach=socket, max_lod=max_lod)
    g.props["mm_attach_label"] = name.split("_detail")[0] if socket != "helmet_attachment" else "helmet"
    return g
